### PR TITLE
Facebook

### PR DESCRIPTION
**Pull request by edgarrambo**
added a few feature, plus facebok link.

if you have an issue when lauching

rake db: drop
rake db: create
rake db:migrate

### CODE REVIEW

**Comment by ArtBianchini** [comment]
Hey Edgar take a look into the gemfile in order to proceed . Trying updating the gem factory_bot_rails which may be affecting the facebook file.

**Comment by edgarrambo** [comment]
I think that one i # out, about to log on now

**Comment by AlT591** [comment]
Yea I saw it was # out. I think that line was not longer in the github master at all. So it was showing as a conflict... thats my understand. I just deleted it completely to eliminate confusion.

**Comment by edgarrambo** [comment]
Did you merge it ?
I am confused here.
If you created a pull request, it should change it and then merge it into Master.

**Pull request merged**
